### ISSUE TITLE
where is the front source code

### ISSUE THREAD

**Issue by x334085347** [WeBankFinTech/Qualitis#20]
目前Qualitis项目中 , 只在Qualitis/web/app/src/main/resources/static/js 看到有打包压缩后前端代码 , 但是源码缺失 .请问 前端源码目前在哪里 能找到谢谢..

**Comment by howeye** [comment]
Because the front-end code of Qualitis is FES, a front-end framework developed by WeBank, but the FES framework is not currently open source, so the front-end code of Qualitis is not open source for the time being. We will promote Qualitis's front-end open source as soon as possible. We are very sorry about it.

**Comment by Tangjiafeng** [comment]
Recommend you to use the new version of Qualitis.
